import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'Employee Hub';

  employees = [
    {
      first_name: 'Wesley',
      last_name: 'Jewess',
      email: 'wjewess0@github.io',
      gender: 'Male',
      job_title: 'Marketing Manager',
      job_area: 'Marketing',
    },
    {
      first_name: 'Briggs',
      last_name: 'Whitlam',
      email: 'bwhitlam1@elegantthemes.com',
      gender: 'Male',
      job_title: 'Electrical Engineer',
      job_area: 'Human Resources',
    },
    {
      first_name: 'Aldus',
      last_name: 'Pauluzzi',
      email: 'apauluzzi2@myspace.com',
      gender: 'Male',
      job_title: 'Associate Professor',
      job_area: 'Sales',
    },
    {
      first_name: 'Frederic',
      last_name: 'Nand',
      email: 'fnand3@booking.com',
      gender: 'Male',
      job_title: 'Payment Adjustment Coordinator',
      job_area: 'Sales',
    },
    {
      first_name: 'Ambros',
      last_name: 'Whitchurch',
      email: 'awhitchurch4@bloomberg.com',
      gender: 'Male',
      job_title: 'Office Assistant II',
      job_area: 'Marketing',
    },
    {
      first_name: 'Lev',
      last_name: 'Doddemeade',
      email: 'ldoddemeade5@dailymail.co.uk',
      gender: 'Polygender',
      job_title: 'Account Executive',
      job_area: 'Sales',
    },
    {
      first_name: 'Dari',
      last_name: 'Gibberd',
      email: 'dgibberd6@europa.eu',
      gender: 'Female',
      job_title: 'Internal Auditor',
      job_area: 'Marketing',
    },
    {
      first_name: 'Gwenette',
      last_name: 'Milkeham',
      email: 'gmilkeham7@bloomberg.com',
      gender: 'Bigender',
      job_title: 'Geological Engineer',
      job_area: 'Operations',
    },
    {
      first_name: 'Rodolph',
      last_name: 'Deville',
      email: 'rdeville8@fc2.com',
      gender: 'Male',
      job_title: 'Cost Accountant',
      job_area: 'Operations',
    },
    {
      first_name: 'Pavia',
      last_name: 'Fackrell',
      email: 'pfackrell9@simplemachines.org',
      gender: 'Female',
      job_title: 'VP Quality Control',
      job_area: 'Sales',
    },
    {
      first_name: 'Vin',
      last_name: 'Richten',
      email: 'vrichtena@netlog.com',
      gender: 'Female',
      job_title: 'Senior Editor',
      job_area: 'Human Resources',
    },
    {
      first_name: 'Barnett',
      last_name: 'Cromleholme',
      email: 'bcromleholmeb@uiuc.edu',
      gender: 'Male',
      job_title: 'Project Manager',
      job_area: 'Marketing',
    },
    {
      first_name: 'Toinette',
      last_name: 'Braxay',
      email: 'tbraxayc@mayoclinic.com',
      gender: 'Female',
      job_title: 'Developer IV',
      job_area: 'Sales',
    },
    {
      first_name: 'Crissie',
      last_name: 'McLae',
      email: 'cmclaed@epa.gov',
      gender: 'Female',
      job_title: 'Programmer IV',
      job_area: 'Marketing',
    },
    {
      first_name: 'Chlo',
      last_name: 'McMickan',
      email: 'cmcmickane@1688.com',
      gender: 'Female',
      job_title: 'Clinical Specialist',
      job_area: 'Human Resources',
    },
    {
      first_name: 'Tyne',
      last_name: 'Braam',
      email: 'tbraamf@sohu.com',
      gender: 'Female',
      job_title: 'Nurse',
      job_area: 'Operations',
    },
    {
      first_name: 'Alethea',
      last_name: 'Vanlint',
      email: 'avanlintg@networkadvertising.org',
      gender: 'Female',
      job_title: 'Chief Design Engineer',
      job_area: 'Marketing',
    },
    {
      first_name: 'Liva',
      last_name: 'Lenton',
      email: 'llentonh@elegantthemes.com',
      gender: 'Female',
      job_title: 'Senior Quality Engineer',
      job_area: 'Sales',
    },
    {
      first_name: 'Kendre',
      last_name: 'Bilovsky',
      email: 'kbilovskyi@si.edu',
      gender: 'Female',
      job_title: 'Help Desk Operator',
      job_area: 'Marketing',
    },
    {
      first_name: 'Dean',
      last_name: 'Raincin',
      email: 'draincinj@spotify.com',
      gender: 'Male',
      job_title: 'VP Marketing',
      job_area: 'Marketing',
    },
  ];
}
